### ISSUE TITLE
[Bug] AP won't start when ethernet cable is plugged in

### ISSUE THREAD

**Issue by alex-ssom** [LeoRover/LeoOS#12] opened 2021-12-02 14:24 UTC
The access point isn't launched when an ethernet cable is plugged into the Raspberry Pi.

My guess is that the network-online.target returns true as soon as the Ethernet interface gets an IP address from the external DHCP server.

It is worth noting that, there’s no issue if the ethernet cable is plugged in after the AP is launched.

My current solution is to unplug one end of the Ethernet cable before booting up the rover.

**Comment by bjsowa** [comment] 2022-04-08 16:05
Could you please check if the issue occurs with the [newest release](https://github.com/LeoRover/LeoOS/releases/tag/1.0.0rc2)? 

Note that the configuration has been changed and now the WiFi and Ethernet interfaces are bridged on RPi by default.

**Comment by alex-ssom** [comment] 2022-04-08 16:36
I won't have the time to test this for quite a while. I've ended up using a `netplan.io ` custom config on all computers on the network. Far from ideal, but I needed a "quick" fix.

**Comment by bjsowa** [comment] 2022-04-11 17:01
I'm unable to reproduce this issue on the newest release, so I'm closing this issue for now. If you run into this problem again, leave a comment and I'll reopen the issue.

**Closed by bjsowa** 2022-04-11 17:01 UTC
